workflows:
  ios-testflight:
    name: iOS TestFlight Build
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      groups:
        - 7GRRFYZ942
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.lovable.drivervtcdispatch
      vars:
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
        BUNDLE_ID: "com.lovable.drivervtcdispatch"
      node: 20
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          npm ci --legacy-peer-deps
      - name: Build web app
        script: |
          npm run build
      - name: Sync Capacitor
        script: |
          # On recrée le dossier ios pour être sûr qu'il est propre
          rm -rf ios
          npx cap add ios
          npx cap sync ios
      - name: Apply code signing
        script: |
          # Cette étape crée les certificats et le fichier export_options.plist
          xcode-project use-profiles
      - name: Build IPA
        script: |
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME" \
            --export-options-plist $CM_BUILD_DIR/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - "*.dSYM.zip"
    publishing:
      email:
        recipients:
          - fasttransport26@gmail.com
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID

  ios-simulator:
    name: iOS Simulator Build (Test)
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      vars:
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
      node: 20
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          npm ci --legacy-peer-deps
      - name: Build web app
        script: |
          npm run build
      - name: Sync Capacitor
        script: |
          if [ ! -d "ios" ]; then
            npx cap add ios
          fi
          npx cap sync ios
      - name: Build Simulator App
        script: |
          xcodebuild build \
            -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -sdk iphonesimulator \
            -configuration Debug \
            -destination 'platform=iOS Simulator,name=iPhone 15'
    artifacts:
      - build/ios/ipa/*.app
      - /tmp/xcodebuild_logs/*.log

  android-release:
    name: Android Release Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      groups:
        - 7GRRFYZ942
      vars:
        PACKAGE_NAME: "com.lovable.drivervtcdispatch"
      node: 20
      java: 17
    scripts:
      - name: Install dependencies
        script: |
          npm ci --legacy-peer-deps
      - name: Build web app
        script: |
          npm run build
      - name: Sync Capacitor
        script: |
          npx cap sync android
      - name: Set Android SDK location
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > android/local.properties
      - name: Build Android Release
        script: |
          cd android
          ./gradlew bundleRelease
    artifacts:
      - android/app/build/outputs/**/*.aab
    publishing:
      email:
        recipients:
          - fasttransport26@gmail.com

  android-debug:
    name: Android Debug Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      vars:
        PACKAGE_NAME: "com.lovable.drivervtcdispatch"
      node: 20
      java: 17
    scripts:
      - name: Install dependencies
        script: |
          npm ci --legacy-peer-deps
      - name: Build web app
        script: |
          npm run build
      - name: Sync Capacitor
        script: |
          npx cap sync android
      - name: Set Android SDK location
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > android/local.properties
      - name: Build Android Debug
        script: |
          cd android
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - fasttransport26@gmail.com
