workflows:
  ios-testflight:
    name: iOS TestFlight Build
    max_build_duration: 120
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: Codemagic
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.lovable.drivervtcdispatch
      vars:
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
        BUNDLE_ID: "com.lovable.drivervtcdispatch"
        APP_STORE_APP_ID: 0000000000
      node: 20
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          npm ci --legacy-peer-deps
      - name: Build web app
        script: |
          npm run build
      - name: Add iOS platform
        script: |
          if [ ! -d "ios" ]; then
            npx cap add ios
          fi
      - name: Sync Capacitor
        script: |
          npx cap sync ios
      - name: Configure iOS Info.plist
        script: |
          node scripts/configure-ios-info-plist.js
      - name: Configure iOS Capabilities
        script: |
          node scripts/configure-ios-capabilities.js
      - name: Install CocoaPods
        script: |
          cd ios/App && pod install --repo-update
      - name: Set up code signing
        script: |
          keychain initialize
          app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE --create
          keychain add-certificates
          xcode-project use-profiles
      - name: Increment build number
        script: |
          cd ios/App
          LATEST_BUILD_NUMBER=$(app-store-connect get-latest-testflight-build-number "$APP_STORE_APP_ID" || echo "0")
          agvtool new-version -all $((LATEST_BUILD_NUMBER + 1))
      - name: Build IPA
        script: |
          xcode-project build-ipa \
            --workspace "$CM_BUILD_DIR/$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME" \
            --config Release \
            --archive-flags="-destination 'generic/platform=iOS'"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - ios/App/build/App.xcarchive
    publishing:
      email:
        recipients:
          - votre-email@example.com
        notify:
          success: true
          failure: true
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - Beta Testers

  ios-simulator:
    name: iOS Simulator Build (Test)
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      vars:
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
      node: 20
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          npm ci --legacy-peer-deps
      - name: Build web app
        script: |
          npm run build
      - name: Add iOS platform
        script: |
          if [ ! -d "ios" ]; then
            npx cap add ios
          fi
      - name: Sync Capacitor
        script: |
          npx cap sync ios
      - name: Configure iOS Info.plist
        script: |
          node scripts/configure-ios-info-plist.js
      - name: Install CocoaPods
        script: |
          cd ios/App && pod install --repo-update
      - name: Build for Simulator
        script: |
          cd ios/App
          xcodebuild build \
            -workspace App.xcworkspace \
            -scheme App \
            -configuration Debug \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 15 Pro' \
            CODE_SIGNING_ALLOWED=NO
    artifacts:
      - ios/App/build/**/*.app
    publishing:
      email:
        recipients:
          - votre-email@example.com
        notify:
          success: true
          failure: true

  android-release:
    name: Android Release Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      android_signing:
        - driver_vtc_keystore
      groups:
        - google_play_credentials
      vars:
        PACKAGE_NAME: "com.lovable.drivervtcdispatch"
      node: 20
      java: 17
    scripts:
      - name: Install dependencies
        script: |
          npm ci --legacy-peer-deps
      - name: Build web app
        script: |
          npm run build
      - name: Sync Capacitor
        script: |
          npx cap sync android
      - name: Set Android SDK location
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > android/local.properties
      - name: Build Android Release
        script: |
          cd android
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/**/*.apk
      - android/app/build/outputs/**/mapping.txt
    publishing:
      email:
        recipients:
          - votre-email@example.com
        notify:
          success: true
          failure: true

  android-debug:
    name: Android Debug Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      vars:
        PACKAGE_NAME: "com.lovable.drivervtcdispatch"
      node: 20
      java: 17
    scripts:
      - name: Install dependencies
        script: |
          npm ci --legacy-peer-deps
      - name: Build web app
        script: |
          npm run build
      - name: Sync Capacitor
        script: |
          npx cap sync android
      - name: Set Android SDK location
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > android/local.properties
      - name: Build Android Debug
        script: |
          cd android
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - votre-email@example.com
        notify:
          success: true
          failure: true
