workflows:
  ios-testflight:
    name: iOS TestFlight Build
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      groups:
        - 7GRRFYZ942
      vars:
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
        BUNDLE_ID: "com.lovable.drivervtcdispatch"
      xcode: latest
      cocoapods: default
      node: 20
    scripts:
      - name: Install dependencies
        script: |
          npm ci --legacy-peer-deps
      - name: Build web app
        script: |
          npm run build
      - name: Sync Capacitor
        script: |
          if [ ! -d "ios" ]; then
            npx cap add ios
          fi
          npx cap sync ios
      - name: Set up code signing
        script: |
          keychain initialize
          app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE --create
          keychain add-certificates
          xcode-project use-profiles
      - name: Build iOS app
        script: |
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME"
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - fasttransport26@gmail.com
      app_store_connect:
        submit_to_testflight: true
    integrations:
      app_store_connect: 7GRRFYZ942
